
POST http://localhost:5001/api/lists
Content-Type: application/json

{
  "boardId": "62b485f3cabca6a997a6644c",
  "list": {
    "title": "Testing API 2"
  }
}

###

POST http://localhost:5001/api/boards
Content-Type: application/json

{
  "board": {
    "title": "Test Board 1"
  }
}

###

GET http://localhost:5001/api/boards

###

GET http://localhost:5001/api/boards/62b33ee07f460004cca1c7c9